### PR TITLE
Added appveyor CI config.

### PR DESCRIPTION
**Pull request by th3ragex**
The appveyor.yml contains all information which needs to be configured
for appveyor builds. No need to configure appveyor beside connecting
appveyor with github.

Appveyor offers a badge for the build status. Example @ https://github.com/th3ragex/Nitra

NOTE: The PowerShell script will try to download and install the nemerle
setup with the configured  $nemerleVersion .

### CODE REVIEW

**Comment by VladD2** [comment]
What is it?

**Comment by rampelstinskin** [comment]
Looks like spam.

**Comment by th3ragex** [comment]
I tried to add a build server support to this project. Appveyor seems to be the only service which offers building of open source .NET projects for free. I know the PowerShell script looks like garbage...

> Looks like spam.
     And no, i am not associated in any way with that service. It just seemed to be the only working option.

Please give it a try, connect Github with appveyor and add Nitra as project. The .yml file contains the whole build configuration, it should start building without any further adjustments.

**Comment by sirinath** [comment]
New repo is: https://github.com/rsdn/nitra

**Pull request closed without merging**
